### ISSUE TITLE
Add menu to navbar

### ISSUE THREAD

**Issue by FlavioAdamo** [FlavioAdamo/Covid-Vaccines-Tracker#22]
I think it is more correct to delete the share button and replace it with a real menu (Hamburger on mobile) and add the git hub and contributors page to it

**Comment by rahulshawdev** [comment]
can i work on it??

**Comment by Saliou1920** [comment]
Hey, good work in this project.  Can I work on this issue ??

**Comment by FlavioAdamo** [comment]
Sure!

**Comment by FlavioAdamo** [comment]
Fixed by @Saliou1920
