### ISSUE TITLE
Add hover effect on counters on top

### ISSUE THREAD

**Issue by FlavioAdamo** [FlavioAdamo/Covid-Vaccines-Tracker#23]

**Comment by d4rkener** [comment]
hey

**Comment by d4rkener** [comment]
can i work on the project??

**Comment by FlavioAdamo** [comment]
Sure.

**Comment by d4rkener** [comment]
what i have to do??

**Comment by FlavioAdamo** [comment]
You have to add an `:hover` effect to the counter on  the top of the page similar to the hover of the accordions

**Comment by d4rkener** [comment]
okk

**Comment by d4rkener** [comment]
should I create a different branch???

**Comment by d4rkener** [comment]
can you send a screenshot of what I have to update please I am kinda confused??

**Comment by FlavioAdamo** [comment]
![image](https://user-images.githubusercontent.com/46765573/119257334-16c6a280-bbc5-11eb-9a45-85067870db5b.png)

When you move the cursor over these counters, nothing happens, and that's what we need to change. If you move the mouse over a continent or a country, the text gets bigger, the best thing to do would be to replicate the same behavior to the counters in the photo above

**Comment by d4rkener** [comment]
I need to do hover on both boxes( greenish box and white box )

**Comment by FlavioAdamo** [comment]
Exactly

**Comment by d4rkener** [comment]
when someone hovers the box I need to increase the font size of both the number and the p tag

**Comment by FlavioAdamo** [comment]
You have to do what you think is right, if there is a problem in the code I will let you know in the pull request

**Comment by d4rkener** [comment]
sorry for disturbing you I am new to open source stuff that's why

**Comment by FlavioAdamo** [comment]
You can disturb me as much as you want, it is normal to ask a lot of questions at the beginning. I told you that because when you are assigned tasks in the future no one will tell you exactly what to change and how to do it. The important thing is to try and experience
