### ISSUE TITLE
Adapt the style of the searchbar to the design of the Website

### ISSUE THREAD

**Issue by FlavioAdamo** [FlavioAdamo/Covid-Vaccines-Tracker#25]

**Comment by dkoode** [comment]
Hey there, can I work on this project?

**Comment by FlavioAdamo** [comment]
Sure!

**Comment by dkoode** [comment]
I have finished designing. If it is ok for you, I can create a pull request. However, if there are things you want me to add, I can add them.
It looks like this now,
![change](https://user-images.githubusercontent.com/81515348/119259871-edb00d00-bbd8-11eb-96ce-f5696be98c4b.PNG)

**Comment by FlavioAdamo** [comment]
I like it!

**Comment by dkoode** [comment]
Thank you! I've created a pull request.
