### ISSUE TITLE
Show filterDiv once the page is loaded.

### ISSUE THREAD

**Issue by FlavioAdamo** [FlavioAdamo/Covid-Vaccines-Tracker#38]
Before the page is fully loaded, you see a white screen with only the search bar and the filter dropdown. I think it would be better if they were loaded once the page is fully loaded

**Comment by Kaushal-Panchal** [comment]
Any suggestions, how to do that? As we are using vanilla JS I am not sure how we manage state here

**Comment by FlavioAdamo** [comment]
You can use `$("#id").show()` or `$("#id").hide()` with jquery.
I suggest to hide by default the filterDiv, and than when all the accordion are loaded  => `$("#filterDiv").show()`
