### ISSUE TITLE
Improve search performance

### ISSUE THREAD

**Issue by FlavioAdamo** [FlavioAdamo/Covid-Vaccines-Tracker#39]
The search lag on smartphones and PCs from a few years ago.

**Comment by benjiww** [comment]
Will give this a crack.

If I can't create anything special I'll just change it from: look for any match with the string typed, to: look for a match in the same index location as the typed characters.

I.e: typing "uni" comes up with only "United States, United ..." as opposed to including "Tunisia" and the like.

Let me know if you would be ok with this outcome, or you want to maintain the .includes method. Cheers.

**Comment by FlavioAdamo** [comment]
I think it is more correct in the way you just said. I will wait for the pull request, thank you very much!
