### ISSUE TITLE
Make the website online

### ISSUE THREAD

**Issue by ghost** [FlavioAdamo/Covid-Vaccines-Tracker#43]
I think that it would be pretty cool if this was actually online, as it is a good looking project that looks very useful. Using a service like Netlify would simplify things as you can tie it to your GitHub so everything is automated, and all for free. Or through GitHub Pages.

**Comment by Keilo75** [comment]
This website is online and can be reached through the domain https://covidvaccinetrack.com/.
@FlavioAdamo, maybe you should edit the README.md file and add the link there to avoid further confusion?

**Comment by FlavioAdamo** [comment]
@IronVeil the website is online, I just updated the readme.
@Keilo75 Can you reach me at flavioadamo.adams@gmail.com?

**Comment by Keilo75** [comment]
Hello, sorry to ask, but why? I don't really like giving away my private email address and I currently don't have time to set up a new one. Is there any other way I can contact you, e. g. through Reddit?

**Comment by FlavioAdamo** [comment]
Sure, no problem! My reddit nickname is FlavioAd
