### ISSUE TITLE
Oversized country_counters formatting on mobile

### ISSUE THREAD

**Issue by benjiww** [FlavioAdamo/Covid-Vaccines-Tracker#50]
On mobile the vaccine data boxes are vertically oversized (see below). Requesting sorting the formatting so it remains similar to the ratios on large monitor devices (PC, laptop etc.).

Cheers.

![image](https://user-images.githubusercontent.com/62560256/119484473-f7a74c80-bd4d-11eb-8089-081ed0634665.png)
![image](https://user-images.githubusercontent.com/62560256/119484502-ff66f100-bd4d-11eb-91cd-cce26fe1d236.png)
![image](https://user-images.githubusercontent.com/62560256/119484518-042ba500-bd4e-11eb-8b01-d4413edbf410.png)
![image](https://user-images.githubusercontent.com/62560256/119484539-0857c280-bd4e-11eb-8580-467de95cd6ae.png)

**Comment by FlavioAdamo** [comment]
FIxed on the production website by adding `max-height`.
This is only happening on iphone, i dont know why.

**Comment by KyleCroxall** [comment]
Yeah I was worried it was just me with this issue, I couldn't replicate it in Dev Tools using the iPhone X template.
