### ISSUE TITLE
Add Flags to country.html

### ISSUE THREAD

**Issue by FlavioAdamo** [FlavioAdamo/Covid-Vaccines-Tracker#53]
https://www.countryflags.io/

**Comment by KyleCroxall** [comment]
Currently trying to sort this out. Should I download all the flag .png's from that website into a folder so we don't need to make hundreds of requests to www.countryflags.io every time a user opens the page? I don't know what's most efficient - and I also don't know if that would increase the server bandwidth needed significantly. What do you think @FlavioAdamo?

**Comment by FlavioAdamo** [comment]
The flags must be added in country.html.
Then there will be only the request of the selected country.

**Comment by KyleCroxall** [comment]
Oops I was trying to put each flag below each name on the main page, that's why I was worried about so many requests haha!
