### ISSUE TITLE
Dynamic <title> country.html

### ISSUE THREAD

**Issue by FlavioAdamo** [FlavioAdamo/Covid-Vaccines-Tracker#55]
It would be cool if the `<title>` in country.html dynamically change based on the selected country.

**Comment by HeyReggie** [comment]
I'm happy to tackle this. Are you wanting the title to just simply be the country name? Or do you want Covid Vaccine Track | 'country name' ? Edit: In looking at it, I think keeping the Covid Vaccine Track | looks better. I'll submit a pull request.
