### ISSUE TITLE
.currentVaccineNumber takes 2 row when the number exceeds one billion on mobile 

### ISSUE THREAD

**Issue by FlavioAdamo** [FlavioAdamo/Covid-Vaccines-Tracker#68]
![image](https://user-images.githubusercontent.com/46765573/120829763-0ff14580-c55e-11eb-90f6-9daa3a550928.png)

**Comment by benjiww** [comment]
To clarify, the syringe is meant to sit to the left on the same row as the count.

**Comment by godwin-morwin** [comment]
Hi @FlavioAdamo , @benjiww .
i do like to work on this issue

**Comment by FlavioAdamo** [comment]
@Godwindaniel10  Sure!

**Comment by godwin-morwin** [comment]
ok , i got it ...
