### ISSUE TITLE
Make the title cards for country.html look more natural

### ISSUE THREAD

**Issue by benjiww** [FlavioAdamo/Covid-Vaccines-Tracker#69]
The title card in country.html which contains the country name looks a little jarring (not quite right). Anyone wanna try and make it look a bit more natural? Cheers.

<img width="1027" alt="Screenshot 2021-06-04 at 19 05 47" src="https://user-images.githubusercontent.com/62560256/120844825-e0473b00-c567-11eb-8089-519c54842577.png">

**Comment by godwin-morwin** [comment]
hi @benjiww .
i do like to work on this issue

**Comment by FlavioAdamo** [comment]
Done!

**Comment by godwin-morwin** [comment]
@FlavioAdamo ok on it

**Comment by godwin-morwin** [comment]
hi , @benjiww , can you be more clear on what you want me to do to the country title section?

**Comment by benjiww** [comment]
> hi , @benjiww , can you be more clear on what you want me to do to the country title section?

Hey @Godwindaniel10 ,

It's really whatever you feel is right. I think you should make the bottom corners as rounded as the top two, and change the background colour to white, making the borders the same consistent with other white cards on the index.html.

No wrong answers though - just make it consistent with the rest of the site.

**Comment by godwin-morwin** [comment]
@benjiww ok ,now I have a clearity 👍
