### ISSUE TITLE
Remove ( Contribute ) text  beside the github icon when hovering on the icon

### ISSUE THREAD

**Issue by godwin-morwin** [FlavioAdamo/Covid-Vaccines-Tracker#75]
The ( contribute ) text beside the GitHub icon is not compatible there. it should be removed because the GitHub icon has a title that defines the (Contribute text ) beside it. 

https://user-images.githubusercontent.com/54848535/120881104-a5c0bb00-c5c6-11eb-978f-8dd186347120.mp4

**Comment by FlavioAdamo** [comment]
You are right! It's a lot better in this way

**Comment by godwin-morwin** [comment]
@FlavioAdamo Right .-.
